[build]
  command = "ng build --localize"
  publish = "dist/portfolio/browser"

[[redirects]]
  from = "/en-US/*"
  to = "/en-US/index.html"
  status = 200

[[redirects]]
  from = "/pt/*"
  to = "/pt/index.html"
  status = 200

[[redirects]]
  from = "/en-US"
  to = "/en-US/index.html"
  status = 200

[[redirects]]
  from = "/pt"
  to = "/pt/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/pt/index.html"
  status = 200
