[build]
  command = "ng build --localize"
  publish = "dist/portfolio/browser"

[build]
  command = "ng build"
  publish = "dist/portfolio/browser"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
